spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/panel?serverTimezone=UTC&useSSL=false}
    username: ${MYSQL_USER:panel}
    password: ${MYSQL_PASSWORD:panel}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    locations:
      - classpath:db/migration/mysql
  sql:
    init:
      mode: never