spring:
  application:
    name: support-bot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}
      platform: ${SQL_INIT_PLATFORM:sqlite}
      schema-locations: classpath:schema-${spring.sql.init.platform:sqlite}.sql
  main:
    web-application-type: none

support-bot:
  token: ${TELEGRAM_BOT_TOKEN:YOUR_TELEGRAM_BOT_TOKEN}
  username: ${TELEGRAM_BOT_USERNAME:your_bot_username}
  channel-id: ${GROUP_CHAT_ID:0}
  attachments-dir: ${APP_STORAGE_ATTACHMENTS:attachments}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
